# Generated by Django 5.2 on 2025-06-24 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
        ('study', '0012_alter_usertestattempt_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='challengeattempt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='challengeattempt',
            name='is_ready',
            field=models.BooleanField(default=False, help_text='Indicates if the user is ready to start.', verbose_name='is ready'),
        ),
        migrations.AlterField(
            model_name='challengeattempt',
            name='question_attempts',
            field=models.ManyToManyField(blank=True, related_name='challenge_context', to='study.userquestionattempt', verbose_name='Question Attempts'),
        ),
        migrations.AlterField(
            model_name='challengeattempt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='challengeattempt',
            index=models.Index(fields=['challenge', 'user'], name='challenges__challen_fea7f8_idx'),
        ),
    ]
